#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    purge)
        SERVICE_XPATH_NAME="mediabrowser"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_delete "${SERVICE_XPATH}"
        fi
######################
        if [ -f "/var/run/${SERVICE_XPATH_NAME}/${SERVICE_XPATH_NAME}.pid" ]; then
            PID=$(cat /var/run/${SERVICE_XPATH_NAME}/${SERVICE_XPATH_NAME}.pid);
            kill -0 $PID 2>/dev/null;

            if [ $? -eq 0 ]; then
                kill -9 $PID;
            fi
        fi

        rm -rf /opt/${SERVICE_XPATH_NAME}
        rm -f /etc/${SERVICE_XPATH_NAME}.conf
        rm -Rf /var/run/${SERVICE_XPATH_NAME}
        userdel -r ${SERVICE_XPATH_NAME}
######################
    ;;

    remove)
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
