#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

if [ "$1" = "purge" ]; then
    SERVICE="mediabrowser"
    update-rc.d ${SERVICE} stop
fi

exit 0
